config/routes.rb
Dvporgcom::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#welcome'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :projects, :only => [:show]
  resources :news, :only => [:show, :index]
  get "pages/design"
  get "pages/development"
  get "pages/seo_optimization"
  get "pages/works"
  get "pages/team"
  get "pages/contacts"
  resources :pages, :only => [:show]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :project

  has_attached_file :photo,
                    :styles => { :small => "50x50>",
                                 :for_gallery => "200x200>",
                                 :normal => "700x700>" },
                    :url  => "/images/gallery/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/images/gallery/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 2.megabytes
  validates_attachment_content_type :photo,
                                    :content_type => ['image/jpg', 'image/jpeg', 'image/gif', 'image/png']

  attr_accessible :photo, :project_id
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_one :image
  attr_accessible :date, :description, :title, :image_attributes

  accepts_nested_attributes_for :image,
                                :allow_destroy => :true,
                                :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :initial_layout

  def initial_layout
    @layout_pages = Page.all
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def show
    @news = News.find(params[:id])
  end

  def index
    @news = News.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
    @last_projects = Project.last(5)
    @projects = Project.all
    @last_news = News.last(3)
  end

  def show
    @page = Page.find(params[:id])
  end

  def design
  end

  def development
  end

  def seo_optimization
  end

  def works
  end

  def team
  end

  def contacts
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" dir="ltr">
<head>
  <%= yield :head %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <script type="text/javascript">var NREUMQ=NREUMQ||[];NREUMQ.push(["mark","firstbyte",new Date().getTime()]);</script>
  <title>DVPorg</title>
  <link rel="stylesheet" href="/assets/maket/slider.css" type="text/css"/>
  <script type="text/javascript" src="/assets/maket/mootools.js"></script>
  <script type="text/javascript" src="/assets/maket/caption.js"></script>
  <script type="text/javascript" src="/assets/maket/jquery.min.js"></script>
  <script type="text/javascript" src="/assets/maket/jquery.easing.1.2.js"></script>
  <script type="text/javascript" src="/assets/maket/jquery.anythingslider.js"></script>
  <script type="text/javascript" src="/assets/maket/superfish.js"></script>
  <script type="text/javascript">
    jQuery.noConflict();
    jQuery(function($){ $("ul.sf-menu").superfish({hoverClass:'sfHover', pathClass:'active', pathLevels:0, delay:800, animation:{opacity:'show', height:'show', width:'show'}, speed:'def', autoArrows:1, dropShadows:1}) });

  </script>
  <script src="/assets/maket/jcarousellite.js" type="text/javascript"></script>
  <script src="/assets/maket/imagepreloader.js" type="text/javascript"></script>
  <script src="/assets/maket/swfobject.js" type="text/javascript"></script>
  <script src="/assets/maket/cufon-yui.js" type="text/javascript"></script>
  <script src="/assets/maket/cufon-replace.js" type="text/javascript"></script>
  <script src="/assets/maket/Aller_700.font.js" type="text/javascript"></script>
  <script src="/assets/maket/Aller_400.font.js" type="text/javascript"></script>
  <script type="text/javascript">
    var $j = jQuery.noConflict();

    preloadImages([
      '/assets/maket/button1_hover.png',
      '/assets/maket/button_newsletter_hover.png',
      '/assets/maket/prev_hover.png',
      '/assets/maket/button_portfolio_hover.png',
      '/assets/maket/button_hover.png'
    ]);
  </script>
  <script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(window).load(function(){
      $j(".carousel").jCarouselLite({
        btnNext: ".next",
        btnPrev: ".prev"
      });
    });
  </script>
<!--[if lt IE 7]>
    <div style=' clear: both; text-align:center; position: relative;'>
    <a href="http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="http://www.theie6countdown.com/images/upgrade.jpg" border="0"  alt="" /></a>
    </div>
<![endif]-->

</head>
<body id="body" class=" index-page">
  <div class="main">
    <div class="header">
      <div class="header-bg">
        <div class="head">
          <h1 id="logo">
            <a href="/" title="Slicer">
              <img title="Slicer" src="/assets/maket/logo.png" alt="Slicer"/>
            </a>
          </h1>
          <div class="serchmod"></div>
          <div id="nav">
            <ul class="menu sf-menu sf-horizontal">
              <li class="first-child item53 home">
                <a href="/">
                  <span>Home</span>
                </a>
              </li>
              <li class="parent item55 design">
                <a href="<%= pages_design_path %>">
                  <span>Design</span>
                </a>
                <ul>
                  <li class="parent item59">
                    <a href="#">
                      <span>Web</span>
                    </a>
                    <ul>
                      <li class="first-child item97">
                        <a href="#">
                          <span>Print</span>
                        </a>
                      </li>
                      <li class="last-child item98">
                        <a href="#">
                          <span>Brandbook</span>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="item60">
                    <a href="#">
                      <span>Print</span>
                    </a>
                  </li>
                  <li class="last-child item62">
                    <a href="#">
                      <span>Brandbook</span>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="item54 development">
                <a href="<%= pages_development_path %>">
                  <span>Development</span>
                </a>
              </li>
              <li class="item104 works">
                <a href="<%= pages_works_path %>">
                  <span>Works</span>
                </a>
              </li>
              <li class="item105 team">
                <a href="<%= pages_team_path %>">
                  <span>Team</span>
                </a>
              </li>
              <li class="last-child item58 contacts">
                <a href="<%= pages_contacts_path %>">
                  <span>Contacts</span>
                </a>
              </li>
            </ul>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>

<%= yield %>

  <div class="footer">
    <div class="foot_bg">
      <div class="foot">
        <div class="foot_menu">
          <div class="wrapper-box module_menu">
            <div class="boxTitle">
              <div class="title">
                <div class="right-bg">
                  <div class="left-bg">
                    <h3>Social Networks</h3>
                  </div>
                </div>
              </div>
            </div>
            <div class="clear">
              <div class="boxIndent">
                <ul class="menu">
                  <li class="item108">
                    <a href="http://twitter.com">
                      <span>Twitter</span>
                    </a>
                  </li>
                  <li class="item107">
                    <a href="http://facebook.com">
                      <span>Facebook</span>
                    </a>
                  </li>
                  <li class="item106">
                    <a href="http://www.flickr.com">
                      <span>Flickr</span>
                    </a>
                  </li>
                  <li class="item109">
                    <a href="http://blogger.com">
                      <span>Blogger</span>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="quicks-solutions">
          <div class="wrapper-box module">
            <div class="boxTitle">
              <div class="title">
                <div class="right-bg">
                  <div class="left-bg">
                    <h3>Quick Solutions</h3>
                  </div>
                </div>
              </div>
            </div>
            <div class="clear">
              <div class="boxIndent">
                <ul class="foot_list pad">
                  <li><a href="#">Management Consulting</a></li>
                  <li><a href="#">Policy and Regulatory Analysis</a></li>
                  <li><a href="#">Market Assessment</a></li>
                  <li><a href="#">Program Management</a></li>
                </ul>
                <ul class="foot_list">
                  <% @layout_pages.each do |page| %>
                    <li><a href="<%= page_path(page) %>"><%= page.title %></a></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="newsletter">
          <div class="wrapper-box module">
            <div class="boxTitle">
              <div class="title">
                <div class="right-bg">
                  <div class="left-bg">
                    <h3>Newsletter</h3>
                  </div>
                </div>
              </div>
            </div>
            <div class="clear">
              <div class="boxIndent">
                <form action="#" method="post" name="subscribeFormModule" id="subscribeFormModule">
                  <div id="nlr-bg">
                    <div class="newslatter png">
                      <div class="input_news">
                        <input class="moduleInput" type="text" name="email" id="email" size="10" value=""/>
                        <input class="moduleButton png" type="submit" name="Submit" value=""/>
                      </div>
                    </div>
                  </div>
                  <input type="hidden" name="option" value="com_spsnewsletter"/>
                  <input type="hidden" name="task" value="addSubscriber"/>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="copy">DVPorg &copy; 2013
          <a href="dvporg.com">Privacy Policy</a>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript"> Cufon.now(); </script>
<script type="text/javascript">if(!NREUMQ.f){NREUMQ.f=function(){NREUMQ.push(["load",new Date().getTime()]);var e=document.createElement("script");e.type="text/javascript";e.src=(("http:"===document.location.protocol)?"http:":"https:")+"//"+"d1ros97qkrwjf5.cloudfront.net/42/eum/rum.js";document.body.appendChild(e);if(NREUMQ.a)NREUMQ.a();};NREUMQ.a=window.onload;window.onload=NREUMQ.f;};NREUMQ.push(["nrfj","beacon-1.newrelic.com","72d7dcce33","1388850","ZV1TZ0FTVkFVWkwKXlwXcFBHW1dcG3pXDUVXVkVwXFxMQFtVVAZDHVxYQENeWUs=",0,2844,new Date().getTime(),"","","","",""]);</script>
</body>
<%= yield :scripts %>
</html>

app/views/news/index.html.erb
<div class="news_index">
  <table>
    <tr>
      <td>Date</td>
      <td>Title</td>
    </tr>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.created_at.strftime("%m/%d") %></td>
        <td><%= link_to news.title, news %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/news/show.html.erb
<div class="news_show">
  <p><h1><%= @news.title %></h1></p>
  <p><%== @news.content %></p>
</div>

app/views/pages/contacts.html.erb
<div class='pages'>
  contacts info
</div>

app/views/pages/design.html.erb
<div class='pages'>
  design info
</div>

app/views/pages/development.html.erb
<div class='pages'>
  development info
</div>

app/views/pages/seo_optimization.html.erb
<div class='pages'>
  seo optimization info
</div>

app/views/pages/show.html.erb
<div class="news_show">
  <p><h1><%= @page.title %></h1></p>
  <p><%== @page.content %></p>
</div>

app/views/pages/team.html.erb
<div class='pages'>
  team info
</div>

app/views/pages/welcome.html.erb
<div class="slide_bg_tail">
  <div class="slide_bg">
    <div class="slides">
      <script type="text/javascript" language="javascript">
        var $asj = jQuery.noConflict();
        $asj(function () {
          function formatText(index, panel) {
          return index + "";
          }
          $asj('.anythingSlider').anythingSlider({
            easing: "easeInOutExpo",
            autoPlay: true,
            delay: 8000,
            showStartStop: false,
            startStopped: false,
            animationTime: 600,
            hashTags: true,
            buildNavigation: true,
            pauseOnHover: false,
            startText: "Start",
            stopText: "Stop",
            navigationFormatter: formatText
          });
        });
      </script>
      <div class="anythingSlider">
        <div class="wrapper">
          <ul>
            <% @last_projects.each_with_index do |project, i| %>
              <li id='slide<%= i %>'>
                <p>
                  <img class="fleft" src="<%= project.image.photo.url(:normal) %>" border="0"/>
                  <span class="text-1"><%= project.title %></span>
                  <span class="text-2"><%= project.project_type %></span>
                </p>
                <p class="portfolio-p"><%= project.description %></p>
                <p>
                  <a class="read_portfolio" href="<%= project_path(project) %>"></a>
                </p>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="content_bg">
  <div class="top-title">
    <div class="wrapper-box module">
      <div class="clear">
        <div class="boxIndent">
          <h2>We produce designs that are creative</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="cols_bg_bottom">
    <div class="cols">
      <div class="col-1">
        <div class="wrapper-box module">
          <div class="boxTitle">
            <div class="title">
              <div class="right-bg">
                <div class="left-bg">
                  <h3>Design</h3>
                </div>
              </div>
            </div>
          </div>
          <div class="clear">
            <div class="boxIndent">
              <p>Lorem ipsum dolor sit amet, consec tetuer adipiscing elit. Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis</p>
              <p>
                <a class="button" href="<%= pages_design_path %>">Read More</a>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-2">
        <div class="wrapper-box module">
          <div class="boxTitle">
            <div class="title">
              <div class="right-bg">
                <div class="left-bg">
                  <h3>Development</h3>
                </div>
              </div>
            </div>
          </div>
          <div class="clear">
            <div class="boxIndent">
              <p>Lorem ipsum dolor sit amet, consec tetuer adipiscing elit. Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis</p>
              <p>
                <a class="button" href="<%= pages_development_path %>">Read More</a>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-3">
        <div class="wrapper-box module">
          <div class="boxTitle">
            <div class="title">
              <div class="right-bg">
                <div class="left-bg">
                  <h3>SEO Optimization</h3>
                </div>
              </div>
            </div>
          </div>
          <div class="clear">
            <div class="boxIndent">
              <p>Lorem ipsum dolor sit amet, consec tetuer adipiscing elit. Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis</p>
              <p>
                <a class="button" href="<%= pages_seo_optimization_path %>">Read More</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="slide-recent_bg">
    <div class="slide-recent">
      <div class="wrapper-box module">
        <div class="boxTitle">
          <div class="title">
            <div class="right-bg">
              <div class="left-bg">
                <h3>Recent Works</h3>
              </div>
            </div>
          </div>
        </div>
        <div class="clear2">
          <div class="boxIndent">
            <div class="carousel-box">
              <button class="prev"></button>
              <button class="next"></button>
              <div class="inner">
                <div class="carousel">
                  <ul>
                    <% @projects.each do |project| %>
                      <li>
                        <a href="<%= project_path(project) %>">
                          <img src="<%= project.image.photo.url(:for_gallery) %>" border="0" width="138" height="138"/>
                        </a>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="date">
    <div class="cols2">
      <% @last_news.each_with_index do |news, i| %>
        <div class="col-<%= i+4 %>">
          <div class="wrapper-box module">
            <div class="boxTitle">
              <div class="title">
                <div class="right-bg">
                  <div class="left-bg">
                    <h3><%= news.created_at.strftime("%m %d") %></h3>
                  </div>
                </div>
              </div>
            </div>
            <div class="clear">
              <div class="boxIndent">
                <p><%= Sanitize.clean(news.content[0..250])+'...' %></p>
                <p>
                  <a class="button" href="<%= news_path(news) %>">Read more</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="wrapper-content content-top ">
    <div class="grey_bg">
      <div id="content">
        <div class="clear">
          <div class="container">
            <div class="clear">
              <table class="blogindex-page" cellpadding="0" cellspacing="0"></table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/works.html.erb
<div class='pages'>
  works info
</div>

app/views/projects/show.html.erb
<div class="project_show">
  <p><%= image_tag @project.image.photo.url(:normal) %></p>
  <p><%= @project.title %></p>
  <p><%= @project.description %></p>
  <p><%= @project.date %></p>
  <p><%= @project.site_url %></p>
</div>